import type { Deck } from '../types';

export const greetingsDeck: Deck = {
  id: 'greetings',
  name: 'Greetings & Basics',
  description: 'Essential German greetings and basic phrases',
  cards: [
    { id: 'g1', de: 'Hallo', en: 'Hello', partOfSpeech: 'phrase' },
    { id: 'g2', de: 'Guten Morgen', en: 'Good morning', partOfSpeech: 'phrase' },
    { id: 'g3', de: 'Guten Tag', en: 'Good day', partOfSpeech: 'phrase' },
    { id: 'g4', de: 'Guten Abend', en: 'Good evening', partOfSpeech: 'phrase' },
    { id: 'g5', de: 'Gute Nacht', en: 'Good night', partOfSpeech: 'phrase' },
    { id: 'g6', de: 'Tschüss', en: 'Bye', partOfSpeech: 'phrase' },
    { id: 'g7', de: 'Auf Wiedersehen', en: 'Goodbye', partOfSpeech: 'phrase' },
    { id: 'g8', de: 'Danke', en: 'Thank you', partOfSpeech: 'phrase' },
    { id: 'g9', de: 'Bitte', en: 'Please / You\'re welcome', partOfSpeech: 'phrase' },
    { id: 'g10', de: 'Entschuldigung', en: 'Excuse me / Sorry', partOfSpeech: 'phrase' },
    { id: 'g11', de: 'Ja', en: 'Yes', partOfSpeech: 'phrase' },
    { id: 'g12', de: 'Nein', en: 'No', partOfSpeech: 'phrase' },
    { id: 'g13', de: 'Wie geht es Ihnen?', en: 'How are you? (formal)', partOfSpeech: 'phrase' },
    { id: 'g14', de: 'Wie geht\'s?', en: 'How are you? (informal)', partOfSpeech: 'phrase' },
    { id: 'g15', de: 'Gut', en: 'Good', partOfSpeech: 'adj' },
  ],
};

export const numbersDeck: Deck = {
  id: 'numbers',
  name: 'Numbers 1-20',
  description: 'Basic German numbers',
  cards: [
    { id: 'n1', de: 'eins', en: 'one', partOfSpeech: 'adj' },
    { id: 'n2', de: 'zwei', en: 'two', partOfSpeech: 'adj' },
    { id: 'n3', de: 'drei', en: 'three', partOfSpeech: 'adj' },
    { id: 'n4', de: 'vier', en: 'four', partOfSpeech: 'adj' },
    { id: 'n5', de: 'fünf', en: 'five', partOfSpeech: 'adj' },
    { id: 'n6', de: 'sechs', en: 'six', partOfSpeech: 'adj' },
    { id: 'n7', de: 'sieben', en: 'seven', partOfSpeech: 'adj' },
    { id: 'n8', de: 'acht', en: 'eight', partOfSpeech: 'adj' },
    { id: 'n9', de: 'neun', en: 'nine', partOfSpeech: 'adj' },
    { id: 'n10', de: 'zehn', en: 'ten', partOfSpeech: 'adj' },
    { id: 'n11', de: 'elf', en: 'eleven', partOfSpeech: 'adj' },
    { id: 'n12', de: 'zwölf', en: 'twelve', partOfSpeech: 'adj' },
    { id: 'n13', de: 'dreizehn', en: 'thirteen', partOfSpeech: 'adj' },
    { id: 'n14', de: 'vierzehn', en: 'fourteen', partOfSpeech: 'adj' },
    { id: 'n15', de: 'fünfzehn', en: 'fifteen', partOfSpeech: 'adj' },
    { id: 'n16', de: 'sechzehn', en: 'sixteen', partOfSpeech: 'adj' },
    { id: 'n17', de: 'siebzehn', en: 'seventeen', partOfSpeech: 'adj' },
    { id: 'n18', de: 'achtzehn', en: 'eighteen', partOfSpeech: 'adj' },
    { id: 'n19', de: 'neunzehn', en: 'nineteen', partOfSpeech: 'adj' },
    { id: 'n20', de: 'zwanzig', en: 'twenty', partOfSpeech: 'adj' },
  ],
};

export const daysDeck: Deck = {
  id: 'days',
  name: 'Days & Time',
  description: 'Days of the week and time-related words',
  cards: [
    { id: 'd1', de: 'Montag', en: 'Monday', article: 'der', partOfSpeech: 'noun' },
    { id: 'd2', de: 'Dienstag', en: 'Tuesday', article: 'der', partOfSpeech: 'noun' },
    { id: 'd3', de: 'Mittwoch', en: 'Wednesday', article: 'der', partOfSpeech: 'noun' },
    { id: 'd4', de: 'Donnerstag', en: 'Thursday', article: 'der', partOfSpeech: 'noun' },
    { id: 'd5', de: 'Freitag', en: 'Friday', article: 'der', partOfSpeech: 'noun' },
    { id: 'd6', de: 'Samstag', en: 'Saturday', article: 'der', partOfSpeech: 'noun' },
    { id: 'd7', de: 'Sonntag', en: 'Sunday', article: 'der', partOfSpeech: 'noun' },
    { id: 'd8', de: 'heute', en: 'today', partOfSpeech: 'adv' },
    { id: 'd9', de: 'morgen', en: 'tomorrow', partOfSpeech: 'adv' },
    { id: 'd10', de: 'gestern', en: 'yesterday', partOfSpeech: 'adv' },
  ],
};

export const verbsDeck: Deck = {
  id: 'common-verbs',
  name: 'Common Verbs',
  description: 'Essential German verbs',
  cards: [
    { id: 'v1', de: 'sein', en: 'to be', partOfSpeech: 'verb', note: 'Irregular verb' },
    { id: 'v2', de: 'haben', en: 'to have', partOfSpeech: 'verb', note: 'Irregular verb' },
    { id: 'v3', de: 'gehen', en: 'to go', partOfSpeech: 'verb' },
    { id: 'v4', de: 'machen', en: 'to do/make', partOfSpeech: 'verb' },
    { id: 'v5', de: 'sprechen', en: 'to speak', partOfSpeech: 'verb' },
    { id: 'v6', de: 'lernen', en: 'to learn', partOfSpeech: 'verb' },
    { id: 'v7', de: 'kommen', en: 'to come', partOfSpeech: 'verb' },
    { id: 'v8', de: 'sehen', en: 'to see', partOfSpeech: 'verb' },
    { id: 'v9', de: 'essen', en: 'to eat', partOfSpeech: 'verb' },
    { id: 'v10', de: 'trinken', en: 'to drink', partOfSpeech: 'verb' },
    { id: 'v11', de: 'wohnen', en: 'to live/reside', partOfSpeech: 'verb' },
    { id: 'v12', de: 'arbeiten', en: 'to work', partOfSpeech: 'verb' },
  ],
};

export const a1BasicsDeck: Deck = {
  id: 'a1-basics',
  name: 'A1 Basics',
  description: 'Basic nouns and words for A1 level',
  cards: [
    { id: 'a1', de: 'Mann', en: 'man', article: 'der', partOfSpeech: 'noun' },
    { id: 'a2', de: 'Frau', en: 'woman', article: 'die', partOfSpeech: 'noun' },
    { id: 'a3', de: 'Kind', en: 'child', article: 'das', partOfSpeech: 'noun' },
    { id: 'a4', de: 'Haus', en: 'house', article: 'das', partOfSpeech: 'noun' },
    { id: 'a5', de: 'Auto', en: 'car', article: 'das', partOfSpeech: 'noun' },
    { id: 'a6', de: 'Buch', en: 'book', article: 'das', partOfSpeech: 'noun' },
    { id: 'a7', de: 'Tisch', en: 'table', article: 'der', partOfSpeech: 'noun' },
    { id: 'a8', de: 'Stuhl', en: 'chair', article: 'der', partOfSpeech: 'noun' },
    { id: 'a9', de: 'Tür', en: 'door', article: 'die', partOfSpeech: 'noun' },
    { id: 'a10', de: 'Fenster', en: 'window', article: 'das', partOfSpeech: 'noun' },
    { id: 'a11', de: 'Wasser', en: 'water', article: 'das', partOfSpeech: 'noun' },
    { id: 'a12', de: 'Brot', en: 'bread', article: 'das', partOfSpeech: 'noun' },
    { id: 'a13', de: 'Milch', en: 'milk', article: 'die', partOfSpeech: 'noun' },
    { id: 'a14', de: 'Kaffee', en: 'coffee', article: 'der', partOfSpeech: 'noun' },
    { id: 'a15', de: 'Tee', en: 'tea', article: 'der', partOfSpeech: 'noun' },
  ],
};

export const travelPhrasebookDeck: Deck = {
  id: 'travel-phrasebook',
  name: 'Travel Phrasebook',
  description: 'Useful phrases for traveling in Germany',
  cards: [
    { id: 't1', de: 'Wo ist...?', en: 'Where is...?', partOfSpeech: 'phrase' },
    { id: 't2', de: 'Wie viel kostet das?', en: 'How much does this cost?', partOfSpeech: 'phrase' },
    { id: 't3', de: 'Ich verstehe nicht', en: 'I don\'t understand', partOfSpeech: 'phrase' },
    { id: 't4', de: 'Sprechen Sie Englisch?', en: 'Do you speak English?', partOfSpeech: 'phrase' },
    { id: 't5', de: 'Ich brauche Hilfe', en: 'I need help', partOfSpeech: 'phrase' },
    { id: 't6', de: 'Die Rechnung, bitte', en: 'The bill, please', partOfSpeech: 'phrase' },
    { id: 't7', de: 'Wo ist die Toilette?', en: 'Where is the bathroom?', partOfSpeech: 'phrase' },
    { id: 't8', de: 'Ein Ticket nach...', en: 'One ticket to...', partOfSpeech: 'phrase' },
    { id: 't9', de: 'Ich bin verloren', en: 'I am lost', partOfSpeech: 'phrase' },
    { id: 't10', de: 'Können Sie mir helfen?', en: 'Can you help me?', partOfSpeech: 'phrase' },
  ],
};

export const sentencesDeck: Deck = {
  id: 'german-sentences',
  name: 'German Sentences',
  description: 'Complete sentences for real-world conversations',
  cards: [
    // Greetings & Introductions
    { id: 's1', de: 'Hallo!', en: 'Hello!', partOfSpeech: 'phrase' },
    { id: 's2', de: 'Guten Morgen!', en: 'Good morning!', partOfSpeech: 'phrase' },
    { id: 's3', de: 'Guten Tag!', en: 'Good day!', partOfSpeech: 'phrase' },
    { id: 's4', de: 'Guten Abend!', en: 'Good evening!', partOfSpeech: 'phrase' },
    { id: 's5', de: 'Tschüss!', en: 'Bye!', partOfSpeech: 'phrase' },
    { id: 's6', de: 'Auf Wiedersehen!', en: 'Goodbye (formal)', partOfSpeech: 'phrase' },
    { id: 's7', de: 'Ich heiße Namit.', en: 'I\'m called Namit.', partOfSpeech: 'phrase' },
    { id: 's8', de: 'Mein Name ist Namit.', en: 'My name is Namit.', partOfSpeech: 'phrase' },
    { id: 's9', de: 'Ich bin Namit.', en: 'I am Namit.', partOfSpeech: 'phrase' },
    { id: 's10', de: 'Freut mich!', en: 'Pleased to meet you!', partOfSpeech: 'phrase' },
    
    // Where You're From / Live
    { id: 's11', de: 'Ich komme aus England.', en: 'I come from England.', partOfSpeech: 'phrase' },
    { id: 's12', de: 'Ich wohne in Leicester.', en: 'I live in Leicester.', partOfSpeech: 'phrase' },
    { id: 's13', de: 'Wohnst du in Deutschland?', en: 'Do you live in Germany?', partOfSpeech: 'phrase' },
    { id: 's14', de: 'Nein, ich wohne nicht in Deutschland.', en: 'No, I don\'t live in Germany.', partOfSpeech: 'phrase' },
    { id: 's15', de: 'Wo wohnst du?', en: 'Where do you live?', partOfSpeech: 'phrase' },
    { id: 's16', de: 'Woher kommst du?', en: 'Where do you come from?', partOfSpeech: 'phrase' },
    { id: 's17', de: 'Woher sind Sie?', en: 'Where are you from? (formal)', partOfSpeech: 'phrase' },
    { id: 's18', de: 'Ich bin Engländer. / Ich bin Engländerin.', en: 'I\'m English (m/f).', partOfSpeech: 'phrase' },
    { id: 's19', de: 'Bist du Deutscher? / Bist du Deutsche?', en: 'Are you German? (m/f)', partOfSpeech: 'phrase' },
    { id: 's20', de: 'Ja, ich bin Deutscher.', en: 'Yes, I\'m German.', partOfSpeech: 'phrase' },
    { id: 's21', de: 'Nein, ich bin kein Deutscher.', en: 'No, I\'m not German.', partOfSpeech: 'phrase' },
    
    // Talking About Language & Skills
    { id: 's22', de: 'Sprichst du Deutsch?', en: 'Do you speak German?', partOfSpeech: 'phrase' },
    { id: 's23', de: 'Ich spreche ein bisschen Deutsch.', en: 'I speak a little German.', partOfSpeech: 'phrase' },
    { id: 's24', de: 'Sprechen Sie Deutsch?', en: 'Do you speak German? (formal)', partOfSpeech: 'phrase' },
    { id: 's25', de: 'Ja, ich spreche Deutsch.', en: 'Yes, I speak German.', partOfSpeech: 'phrase' },
    { id: 's26', de: 'Nein, ich spreche kein Deutsch.', en: 'No, I don\'t speak German.', partOfSpeech: 'phrase' },
    { id: 's27', de: 'Welche Sprachen sprichst du?', en: 'What languages do you speak?', partOfSpeech: 'phrase' },
    { id: 's28', de: 'Ich spreche Englisch und ein bisschen Deutsch.', en: 'I speak English and a little German.', partOfSpeech: 'phrase' },
    
    // Feelings / Well-being
    { id: 's29', de: 'Wie geht es dir?', en: 'How are you?', partOfSpeech: 'phrase' },
    { id: 's30', de: 'Es geht mir gut.', en: 'I\'m good.', partOfSpeech: 'phrase' },
    { id: 's31', de: 'Es geht mir sehr gut, danke!', en: 'I\'m very good, thanks!', partOfSpeech: 'phrase' },
    { id: 's32', de: 'Und dir?', en: 'And you?', partOfSpeech: 'phrase' },
    { id: 's33', de: 'Wie geht es Ihnen?', en: 'How are you? (formal)', partOfSpeech: 'phrase' },
    { id: 's34', de: 'Geht es Ihnen gut?', en: 'Are you well? (formal)', partOfSpeech: 'phrase' },
    { id: 's35', de: 'Es geht mir so lala.', en: 'I\'m so-so.', partOfSpeech: 'phrase' },
    { id: 's36', de: 'Es geht so.', en: 'It\'s okay / could be better.', partOfSpeech: 'phrase' },
    
    // Polite and Formal Forms
    { id: 's37', de: 'Wie heißen Sie?', en: 'What\'s your name? (formal)', partOfSpeech: 'phrase' },
    { id: 's38', de: 'Ich bin Ed. Und Sie?', en: 'I\'m Ed. And you?', partOfSpeech: 'phrase' },
    { id: 's39', de: 'Wo wohnen Sie?', en: 'Where do you live? (formal)', partOfSpeech: 'phrase' },
    { id: 's40', de: 'Wo kommen Sie her?', en: 'Where do you come from? (formal)', partOfSpeech: 'phrase' },
    { id: 's41', de: 'Es geht mir gut. Und Ihnen?', en: 'I\'m fine. And you? (formal)', partOfSpeech: 'phrase' },
    { id: 's42', de: 'Guten Tag, Herr Müller.', en: 'Good day, Mr. Müller.', partOfSpeech: 'phrase' },
    { id: 's43', de: 'Guten Tag, Frau Schmidt.', en: 'Good day, Mrs. Schmidt.', partOfSpeech: 'phrase' },
    
    // Miscellaneous Useful Phrases
    { id: 's44', de: 'Einen schönen Tag noch!', en: 'Have a nice day!', partOfSpeech: 'phrase' },
    { id: 's45', de: 'Danke schön!', en: 'Thank you very much!', partOfSpeech: 'phrase' },
    { id: 's46', de: 'Bitte schön!', en: 'You\'re very welcome!', partOfSpeech: 'phrase' },
    { id: 's47', de: 'Ich arbeite an der Universität.', en: 'I work at the university.', partOfSpeech: 'phrase' },
    { id: 's48', de: 'Ich esse gern Hähnchen.', en: 'I like eating chicken.', partOfSpeech: 'phrase' },
    { id: 's49', de: 'Ich mag Musik.', en: 'I like music.', partOfSpeech: 'phrase' },
    { id: 's50', de: 'Ich habe einen Bruder.', en: 'I have a brother.', partOfSpeech: 'phrase' },
  ],
};

export const nationalitiesDeck: Deck = {
  id: 'nationalities',
  name: 'Nationalities',
  description: 'Learn nationalities in masculine and feminine forms',
  cards: [
    { id: 'nat1', de: 'Franzose / Französin', en: 'French (m/f)', partOfSpeech: 'noun', note: 'from Frankreich' },
    { id: 'nat2', de: 'Italiener / Italienerin', en: 'Italian (m/f)', partOfSpeech: 'noun', note: 'from Italien' },
    { id: 'nat3', de: 'Spanier / Spanierin', en: 'Spanish (m/f)', partOfSpeech: 'noun', note: 'from Spanien' },
    { id: 'nat4', de: 'Amerikaner / Amerikanerin', en: 'American (m/f)', partOfSpeech: 'noun', note: 'from USA' },
    { id: 'nat5', de: 'Deutscher / Deutsche', en: 'German (m/f)', partOfSpeech: 'noun', note: 'from Deutschland' },
    { id: 'nat6', de: 'Schweizer', en: 'Swiss (m/f)', partOfSpeech: 'noun', note: 'from Schweiz - same for both' },
    { id: 'nat7', de: 'Brite / Britin', en: 'British (m/f)', partOfSpeech: 'noun', note: 'from Vereinigtes Königreich' },
    { id: 'nat8', de: 'Engländer / Engländerin', en: 'English (m/f)', partOfSpeech: 'noun', note: 'from England' },
    { id: 'nat9', de: 'Österreicher / Österreicherin', en: 'Austrian (m/f)', partOfSpeech: 'noun', note: 'from Österreich' },
    { id: 'nat10', de: 'Pole / Polin', en: 'Polish (m/f)', partOfSpeech: 'noun', note: 'from Polen' },
    { id: 'nat11', de: 'Russe / Russin', en: 'Russian (m/f)', partOfSpeech: 'noun', note: 'from Russland' },
    { id: 'nat12', de: 'Türke / Türkin', en: 'Turkish (m/f)', partOfSpeech: 'noun', note: 'from Türkei' },
    { id: 'nat13', de: 'Chinese / Chinesin', en: 'Chinese (m/f)', partOfSpeech: 'noun', note: 'from China' },
    { id: 'nat14', de: 'Japaner / Japanerin', en: 'Japanese (m/f)', partOfSpeech: 'noun', note: 'from Japan' },
    { id: 'nat15', de: 'Brasilianer / Brasilianerin', en: 'Brazilian (m/f)', partOfSpeech: 'noun', note: 'from Brasilien' },
  ],
};

export const familyDeck: Deck = {
  id: 'family',
  name: 'Family Members',
  description: 'Learn German family vocabulary with articles',
  cards: [
    { id: 'fam1', de: 'Bruder', en: 'brother', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam2', de: 'Schwester', en: 'sister', article: 'die', partOfSpeech: 'noun' },
    { id: 'fam3', de: 'Kind', en: 'child', article: 'das', partOfSpeech: 'noun' },
    { id: 'fam4', de: 'Eltern', en: 'parents', article: 'die', partOfSpeech: 'noun', note: 'plural only' },
    { id: 'fam5', de: 'Mutter', en: 'mother', article: 'die', partOfSpeech: 'noun' },
    { id: 'fam6', de: 'Vater', en: 'father', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam7', de: 'Onkel', en: 'uncle', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam8', de: 'Tante', en: 'aunt', article: 'die', partOfSpeech: 'noun' },
    { id: 'fam9', de: 'Nichte', en: 'niece', article: 'die', partOfSpeech: 'noun' },
    { id: 'fam10', de: 'Neffe', en: 'nephew', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam11', de: 'Großmutter', en: 'grandmother', article: 'die', partOfSpeech: 'noun', note: 'informal: Oma' },
    { id: 'fam12', de: 'Großvater', en: 'grandfather', article: 'der', partOfSpeech: 'noun', note: 'informal: Opa' },
    { id: 'fam13', de: 'Oma', en: 'grandma', article: 'die', partOfSpeech: 'noun' },
    { id: 'fam14', de: 'Opa', en: 'grandpa', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam15', de: 'Cousin', en: 'male cousin', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam16', de: 'Kusine', en: 'female cousin', article: 'die', partOfSpeech: 'noun' },
    { id: 'fam17', de: 'Freund', en: 'male friend / boyfriend', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam18', de: 'Freundin', en: 'female friend / girlfriend', article: 'die', partOfSpeech: 'noun' },
    { id: 'fam19', de: 'Sohn', en: 'son', article: 'der', partOfSpeech: 'noun' },
    { id: 'fam20', de: 'Tochter', en: 'daughter', article: 'die', partOfSpeech: 'noun' },
  ],
};

export const possessivesDeck: Deck = {
  id: 'possessives',
  name: 'Possessives',
  description: 'Learn possessive pronouns: mein, dein, sein, ihr',
  cards: [
    { id: 'pos1', de: 'mein Bruder', en: 'my brother', partOfSpeech: 'phrase', note: 'masculine - no ending' },
    { id: 'pos2', de: 'meine Schwester', en: 'my sister', partOfSpeech: 'phrase', note: 'feminine - add -e' },
    { id: 'pos3', de: 'mein Kind', en: 'my child', partOfSpeech: 'phrase', note: 'neuter - no ending' },
    { id: 'pos4', de: 'meine Eltern', en: 'my parents', partOfSpeech: 'phrase', note: 'plural - add -e' },
    { id: 'pos5', de: 'dein Freund', en: 'your friend (informal)', partOfSpeech: 'phrase', note: 'masculine - no ending' },
    { id: 'pos6', de: 'deine Freundin', en: 'your friend (informal, f)', partOfSpeech: 'phrase', note: 'feminine - add -e' },
    { id: 'pos7', de: 'sein Vater', en: 'his father', partOfSpeech: 'phrase', note: 'masculine - no ending' },
    { id: 'pos8', de: 'seine Mutter', en: 'his mother', partOfSpeech: 'phrase', note: 'feminine - add -e' },
    { id: 'pos9', de: 'ihr Bruder', en: 'her brother', partOfSpeech: 'phrase', note: 'masculine - no ending' },
    { id: 'pos10', de: 'ihre Schwester', en: 'her sister', partOfSpeech: 'phrase', note: 'feminine - add -e' },
    { id: 'pos11', de: 'Das ist mein Bruder.', en: 'This is my brother.', partOfSpeech: 'phrase' },
    { id: 'pos12', de: 'Das ist meine Schwester.', en: 'This is my sister.', partOfSpeech: 'phrase' },
    { id: 'pos13', de: 'Wie heißt dein Freund?', en: 'What is your friend called?', partOfSpeech: 'phrase' },
    { id: 'pos14', de: 'Sein Bruder spricht Deutsch.', en: 'His brother speaks German.', partOfSpeech: 'phrase' },
    { id: 'pos15', de: 'Ihre Schwester spricht kein Deutsch.', en: "Her sister doesn't speak German.", partOfSpeech: 'phrase' },
  ],
};

export const languagesDeck: Deck = {
  id: 'languages',
  name: 'Languages',
  description: 'Learn how to say different languages in German',
  cards: [
    { id: 'lang1', de: 'Deutsch', en: 'German', partOfSpeech: 'noun' },
    { id: 'lang2', de: 'Englisch', en: 'English', partOfSpeech: 'noun' },
    { id: 'lang3', de: 'Französisch', en: 'French', partOfSpeech: 'noun' },
    { id: 'lang4', de: 'Spanisch', en: 'Spanish', partOfSpeech: 'noun' },
    { id: 'lang5', de: 'Italienisch', en: 'Italian', partOfSpeech: 'noun' },
    { id: 'lang6', de: 'Russisch', en: 'Russian', partOfSpeech: 'noun' },
    { id: 'lang7', de: 'Arabisch', en: 'Arabic', partOfSpeech: 'noun' },
    { id: 'lang8', de: 'Chinesisch', en: 'Chinese', partOfSpeech: 'noun' },
    { id: 'lang9', de: 'Japanisch', en: 'Japanese', partOfSpeech: 'noun' },
    { id: 'lang10', de: 'Portugiesisch', en: 'Portuguese', partOfSpeech: 'noun' },
    { id: 'lang11', de: 'Ich spreche Deutsch.', en: 'I speak German.', partOfSpeech: 'phrase' },
    { id: 'lang12', de: 'Ich spreche ein bisschen Deutsch.', en: 'I speak a little German.', partOfSpeech: 'phrase' },
    { id: 'lang13', de: 'Welche Sprachen sprichst du?', en: 'What languages do you speak?', partOfSpeech: 'phrase' },
    { id: 'lang14', de: 'Ich spreche kein Spanisch.', en: "I don't speak Spanish.", partOfSpeech: 'phrase' },
    { id: 'lang15', de: 'Sprechen Sie Englisch?', en: 'Do you speak English? (formal)', partOfSpeech: 'phrase' },
  ],
};

export const allDecks: Deck[] = [
  greetingsDeck,
  numbersDeck,
  daysDeck,
  verbsDeck,
  a1BasicsDeck,
  travelPhrasebookDeck,
  sentencesDeck,
  nationalitiesDeck,
  familyDeck,
  possessivesDeck,
  languagesDeck,
];
